export const SITUATIONS = [
  "When you see your boss at a swinger party",
  "What you describe at work why your are late",
  "When your blind date is your creepy classmate",
  "When you wake-up with your half-eaten kebab next to your pillow",
  "When your social battery suddenly runs out",
  "What you experience on the way home at 5 o'clock in the morning fully drunk",
  "How according to your description your studies are going if your parents ask you",
  "What you eat in the evening, after you have resolved in the morning to finally eat healthy now",
  "The gym on January 2",
  "What's on your wish list for Santa",
  "The most embarrassing thing that has ever happened to you",
  "How you looked like in 6th grade",
  "How your boss acts at the christmas party",
  "What the worst way to die would be",
  "When you try a risky new fashion trend",
  "How family reunions are now that your siblings are married and have children",
  "When you see your crush on and want to look extra cool",
  "What you give the kids on Halloween",
  "How the pool party actually is after you expected Project X",
  "When you watch Twilight",
  "When you finally receive your letter from Hogwarts",
  "When you leave the party without telling anyone",
  "What you tell when asked how your weekend was",
  "When your parents tell a funny story from your childhood",
  "How your parents describe their way to school",
  "What you wish for when you blow out the birthday candle",
  "When you have one of your crazy dreams again",
  "When you are invited to a party and you know that your ex will be there too",
  "How you arrive, being aware that you are over an hour late",
  "When you forget your headphones and have to ride the train for 10 minutes",
  "When your boyfriend has a slight cold",
  "When you finally get home after a long day of socializing",
  "The first result when you google the person you fucked last night",
  "What you see when your life passes you by before you die",
  "How your parents imagine your job",
  "How you describe yourself on Tinder",
  "What really happened on your last vacation",
  "You at your first day of school",
  "You at your last day of school",
  "How your child self would react if it could see yourself now",
  "What you would do if you would be able to time-travel",
  "When you try a new cooking recipe for the first time",
  "When you tried weed for the first time",
  "You at your worst hangover",
  "The funniest thing that happened when you were drunk",
  "When you and your friends are at vacation",
]
