export const SITUATIONS = [
  "When you see your boss at a swinger party",
  "What you describe at work why your are late",
  "When your blind date is your creepy classmate",
  "When you wake-up with your half-eaten kebab next to your pillow",
  "When your social battery suddenly runs out",
  "What you experience on the way home at 5 o'clock in the morning fully drunk",
  "How according to your description your studies are going if your parents ask you",
  "What you eat in the evening, after you have resolved in the morning to finally eat healthy now",
  "The gym on January 2",
  "What's on your wish list for Santa",
  "The most embarrassing thing that has ever happened to you",
  "How you looked like in 6th grade",
  "How your boss acts at the christmas party",
  "What the worst way to die would be",
  "When you try a risky new fashion trend",
  "How family reunions are now that your siblings are married and have children",
  "When you see your crush on and want to look extra cool",
  "What you give the kids on Halloween",
  "How the pool party actually is after you expected Project X",
  "When you watch Twilight",
  "When you finally receive your letter from Hogwarts",
  "When you leave the party without telling anyone",
  "What you tell when asked how your weekend was",
  "When your parents tell a funny story from your childhood",
  "How your parents describe their way to school",
  "What you wish for when you blow out the birthday candle",
  "When you have one of your crazy dreams again",
  "When you are invited to a party and you know that your ex will be there too",
  "How you arrive, being aware that you are over an hour late",
  "When you forget your headphones and have to ride the train for 10 minutes",
  "When your boyfriend has a slight cold",
  "When you finally get home after a long day of socializing",
  "The first result when you google the person you fucked last night",
  "What you see when your life passes you by before you die",
  "How your parents imagine your job",
  "How you describe yourself on Tinder",
  "What really happened on your last vacation",
  "You at your first day of school",
  "You at your last day of school",
  "How your child self would react if it could see yourself now",
  "What you would do if you would be able to time-travel",
  "When you try a new cooking recipe for the first time",
  "When you tried weed for the first time",
  "You at your worst hangover",
  "The funniest thing that happened when you were drunk",
  "When you and your friends are at vacation",
  "When your coworkers steal your lunch from the office fridge",
  "When your phone dies during an important call",
  "When you accidentally hit \"reply all\" on an embarrassing email",
  "When you finally finish a big project at work",
  "When you have to make small talk with someone you don't like",
  "When you're stuck in traffic on the way to an important meeting",
  "When you're trying to be productive but all your friends are online",
  "When you're trying to be romantic but your partner is more interested in their phone",
  "When you're trying to impress someone with your cooking skills but it doesn't turn out well",
  "When you're trying to be healthy but the smell of fast food is too tempting",
  "When you're trying to take a good selfie but your dog photobombs it",
  "When you're trying to enjoy a concert but the person behind you won't stop talking",
  "When you're trying to be serious but someone makes a pun",
  "When you're trying to be cool but you're just not",
  "When you're trying to be healthy but someone brings donuts to the office",
  "When you're trying to be a good listener but you're too busy thinking about something else.",
  "When you realize you have the same outfit as someone else at a party",
  "When you're trying to be on time but the train is delayed",
  "When you're trying to be cool and order something fancy at a restaurant but can't pronounce it",
  "When you're trying to be serious but someone starts singing",
  "When you're trying to be productive but all you can think about is taking a nap",
  "When you're trying to be cool but you end up spilling your drink",
  "When you're trying to be professional but you get a notification from your dating app",
  "When you're trying to be serious but someone tells a joke",
  "When you're trying to be athletic but you trip over your own feet",
  "When you're trying to be a good listener but you're too busy thinking about what you're going to say next",
  "When you're trying to be cool but you're actually just awkward",
  "When you're trying to be healthy but your favorite unhealthy food is calling your name",
  "When you're trying to be confident but you're actually just nervous",
  "When you're trying to be cool but your phone runs out of battery",
  "When you're trying to be professional but you forget someone's name.",
  "When you're trying to be serious but your phone starts playing music",
  "When you're trying to be healthy but your friends invite you to go out for pizza",
  "When you're trying to be cool but you're actually just clumsy",
  "When you're trying to be professional but you sneeze loudly in a meeting",
  "When you're trying to be a good listener but your mind is elsewhere",
  "When you're trying to be cool but you're actually just nervous",
  "When you're trying to be productive but your internet connection is slow",
  "When you're trying to be cool but you're actually just too tired",
  "When you're trying to be healthy but you're craving chocolate",
  "When you're trying to be confident but you're actually just shy",
  "When you're trying to be cool but you're actually just awkward",
  "When you're trying to be professional but you're really just procrastinating",
  "When you're trying to be healthy but your favorite unhealthy food is too tempting",
  "When you're trying to be serious but someone makes a silly face",
  "When you're trying to be a good listener but you're too busy thinking about your fantasy football team",
]
